name: "Product Designer"
description: "Alex Cican - Product Designer"

url: "http://alexcican.com"
# url: "http://localhost:4000"

# paginate: 10

markdown: rdiscount
permalink: /post/:title/
# pygments: true